apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  collection:
    logs:
      fluentd:
        tolerations:
          - effect: NoSchedule
            key: node
            operator: Equal
            value: logging
          - effect: NoSchedule
            key: node
            operator: Equal
            value: monitoring-registry
      type: fluentd
  logStore:
    elasticsearch:
      nodeCount: 3
      nodeSelector:
        node: logging
      proxy:
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 256Mi
      redundancyPolicy: SingleRedundancy
      resources:
        limits:
          memory: 16Gi
        requests:
          memory: 16Gi
      storage:
        size: 100G
        storageClassName: gp2
      tolerations:
        - effect: NoSchedule
          key: node
          operator: Equal
          value: logging
    retentionPolicy:
      application:
        maxAge: 7d
      audit:
        maxAge: 7d
      infra:
        maxAge: 7d
    type: elasticsearch
  managementState: Managed
  visualization:
    kibana:
      nodeSelector:
        node: logging
      replicas: 1
      tolerations:
        - effect: NoSchedule
          key: node
          operator: Equal
          value: logging
    type: kibana
