apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  managementState: Managed
  collection:
    logs:
      type: fluentd
      fluentd:
        tolerations:
          - effect: NoSchedule
            key: node.ocs.openshift.io/storage
            operator: Equal
            value: 'true'
          - effect: NoSchedule
            key: node
            operator: Equal
            value: logging
          - effect: NoSchedule
            key: node
            operator: Equal
            value: monitoring-registry
          - effect: NoSchedule
            key: infra-internal
            operator: Exists
          - effect: NoSchedule
            key: infra-external
            operator: Exists
  curation:
    type: curator
    curator:
      nodeSelector:
        node: logging
      schedule: 30 3 * * *
      tolerations:
        - effect: NoSchedule
          key: node
          operator: Equal
          value: logging
  logStore:
    type: elasticsearch
    elasticsearch:
      nodeCount: 3
      nodeSelector:
        node: logging
      proxy:
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 256Mi
      redundancyPolicy: SingleRedundancy
      resources:
        requests:
          memory: 16Gi
      storage:
        size: 250G
        storageClassName: ocs-storagecluster-ceph-rbd
      tolerations:
        - effect: NoSchedule
          key: node
          operator: Equal
          value: logging
      retentionPolicy:
        application:
          maxAge: 7d
        audit:
          maxAge: 7d
        infra:
          maxAge: 7d
  visualization:
    type: kibana
    kibana:
      nodeSelector:
        node: logging
      replicas: 1
      tolerations:
        - effect: NoSchedule
          key: node
          operator: Equal
          value: logging
