apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
spec:
  logLevel: Normal
  rolloutStrategy: RollingUpdate
  operatorLogLevel: Normal
  requests:
    read:
      maxWaitInQueue: 0s
    write:
      maxWaitInQueue: 0s
  observedConfig: null
  proxy: {}
  unsupportedConfigOverrides: null
  httpSecret: >-
    9aa4781e17ecb188aa75d7024329c63ab8cc35be392c93fba045d102f0b9ded269da7a905e44401442f9c64266389ab0d6e3b52b4e2ea0894ab95cce33b8c9bc
  replicas: 1
  managementState: Managed
  defaultRoute: true
  nodeSelector:
    node: monitoring-registry
  storage:
    managementState: Managed
    pvc:
      claim: image-registry-storage
  tolerations:
    - effect: NoSchedule
      key: node
      operator: Equal
      value: monitoring-registry
