kind: ConfigMap
apiVersion: v1
metadata:
  name: idm-ca
  namespace: openshift-config
data:
  ca.crt: |-
    -----BEGIN CERTIFICATE-----
    isi cat /etc/ipa/ca.crt
    -----END CERTIFICATE-----
