apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: my-schedule
  namespace: openshift-adp
spec:
  schedule: '*/5 * * * *'
  template:
    includedNamespaces:
      - vm
    storageLocation: oadp-vm-backup-1
    snapshotVolumes: true
