##############

#  CHECK README

##############

apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-workers-timezone
spec:
  config:
    ignition:
      config: {}
      security:
        tls: {}
      timeouts: {}
      version: 3.2.0
    networkd: {}
    passwd: {}
    storage: {}
    systemd:
      units:
        - contents: |
            [Unit]
            Description=set timezone
            After=network-online.target

            [Service]
            Type=oneshot
            ExecStart=timedatectl set-timezone Asia/Jakarta

            [Install]
            WantedBy=multi-user.target
          enabled: true
          name: custom-timezone.service
