kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: use-scc-hostmount-anyuid
  namespace: nfs-storage
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - hostmount-anyuid
