apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  labels:
    network.openshift.io/policy-group: ingress
  name: external-router
  namespace: openshift-ingress-operator
spec:
  defaultCertificate:
    name: default-ingress-tls
    domain: apps-ext.jktclus.gudanggaramtbk.com
  nodePlacement:
    nodeSelector:
      matchLabels:
        node: external-router
        node-role.kubernetes.io/infra: ''
    tolerations:
      - effect: NoSchedule
        key: infra-external
        operator: Exists
  routeSelector:
    matchLabels:
      router: external
