apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: monreg
spec:
  machineConfigSelector:
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values:
          - worker
          - monreg
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/monreg: ''
