###############

# contoh
# Surya Madristrindo

##############

apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  labels:
    network.openshift.io/policy-group: ingress
  name: external-router
  namespace: openshift-ingress-operator
spec:
  domain: external-apps.cluster-l7vjc.l7vjc.sandbox487.opentlc.com #sesuaikan domain
  defaultCertificate:
    name: ingress-certs-2023-07-14 #sesuaikan sertifikat
  nodePlacement:
    nodeSelector:
      matchLabels:
        node: external-router
        node-role.kubernetes.io/infra: ''
    tolerations:
      - effect: NoSchedule
        key: infra-external
        operator: Exists
  routeSelector:
    matchLabels:
      router: external
  namespaceSelector:
    matchLabels:
      environment: dmz
