apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: django-psql-example
    template: django-psql-example
    type: internal # type of route
  name: django-psql-example
  namespace: test-sharding
spec:
  host: django-psql-example-test-sharding.internal-apps.cluster-cxtzd.cxtzd.sandbox1266.opentlc.com
  subdomain: ''
  to:
    kind: Service
    name: django-psql-example
    weight: 100
  wildcardPolicy: None
