apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: django-psql-example
    template: django-psql-example
    type: external # type of route
  name: django-psql-example
  namespace: test-sharding
spec:
  host: django-psql-example-test-sharding.external-apps.cluster-csvlw.csvlw.sandbox1045.opentlc.com
  subdomain: ''
  to:
    kind: Service
    name: django-psql-example
    weight: 100
  wildcardPolicy: None
