apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: django-psql-example-external
  namespace: test-sharding
  labels:
    router: external
spec:
  host: django-psql-example-external.external-apps.cluster-l7vjc.l7vjc.sandbox487.opentlc.com
  subdomain: ''
  to:
    kind: Service
    name: django-psql-example
    weight: 100
  tls:
    termination: edge
  wildcardPolicy: None
