apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: dbroot
  namespace: storage-multiple
spec:
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 15Gi
    storageClassName: ocs-storagecluster-cephfs
  source:
    blank: {}
