apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-csvlw-fjfgb
  name: master
  namespace: openshift-machine-api
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-csvlw-fjfgb
      machine.openshift.io/cluster-api-machineset: cluster-csvlw-fjfgb-master-ap-southeast-1c
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-csvlw-fjfgb
        machine.openshift.io/cluster-api-machine-role: master
        machine.openshift.io/cluster-api-machine-type: master
        machine.openshift.io/cluster-api-machineset: cluster-csvlw-fjfgb-master-ap-southeast-1c
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/master: ''
          node-role.kubernetes.io/control-plane: ''
      providerSpec:
        value:
          ami:
            id: ami-0e60320100241049a
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 100
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: cluster-csvlw-fjfgb-master-profile
          instanceType: c5.4xlarge
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: ap-southeast-1c
            region: ap-southeast-1
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - cluster-csvlw-fjfgb-master-sg
          subnet:
            filters:
              - name: tag:Name
                values:
                  - cluster-csvlw-fjfgb-private-ap-southeast-1c
          tags:
            - name: kubernetes.io/cluster/cluster-csvlw-fjfgb
              value: owned
            - name: email
              value: zfajart@gmail.com
          userDataSecret:
            name: master-user-data
