apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-csvlw-fjfgb
  name: default-router
  namespace: openshift-machine-api
spec:
  replicas: 2
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-csvlw-fjfgb
      machine.openshift.io/cluster-api-machineset: cluster-csvlw-fjfgb-default-router-ap-southeast-1c
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-csvlw-fjfgb
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra
        machine.openshift.io/cluster-api-machineset: cluster-csvlw-fjfgb-default-router-ap-southeast-1c
    spec:
      taints:
        - key: infra-internal
          effect: NoSchedule
      metadata:
        labels:
          node-role.kubernetes.io/infra: ''
          node: default-router
      providerSpec:
        value:
          ami:
            id: ami-0e60320100241049a
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 00
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: cluster-csvlw-fjfgb-worker-profile
          instanceType: c5.xlarge
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: ap-southeast-1c
            region: ap-southeast-1
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - cluster-csvlw-fjfgb-worker-sg
          subnet:
            filters:
              - name: tag:Name
                values:
                  - cluster-csvlw-fjfgb-private-ap-southeast-1c
          tags:
            - name: kubernetes.io/cluster/cluster-csvlw-fjfgb
              value: owned
            - name: email
              value: zfajart@gmail.com
          userDataSecret:
            name: worker-user-data
