apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-rwlwm-gpjp6
  name: logging
  namespace: openshift-machine-api
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-rwlwm-gpjp6
      machine.openshift.io/cluster-api-machineset: cluster-rwlwm-gpjp6-logging-ap-southeast-1c
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-rwlwm-gpjp6
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra
        machine.openshift.io/cluster-api-machineset: cluster-rwlwm-gpjp6-logging-ap-southeast-1c
    spec:
      taints:
        - key: node
          value: logging
          effect: NoSchedule
      metadata:
        labels:
          node-role.kubernetes.io/infra: ''
          node: logging
      providerSpec:
        value:
          userDataSecret:
            name: worker-user-data
          ami:
            id: ami-069a8d5e6af249c74
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                encrypted: true
                iops: 0
                kmsKey:
                  arn: ''
                volumeSize: 100
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: cluster-rwlwm-gpjp6-worker-profile
          instanceType: m5.4xlarge
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: ap-southeast-1c
            region: ap-southeast-1
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - cluster-rwlwm-gpjp6-worker-sg
          subnet:
            filters:
              - name: tag:Name
                values:
                  - cluster-rwlwm-gpjp6-private-ap-southeast-1c
          tags:
            - name: kubernetes.io/cluster/cluster-rwlwm-gpjp6
              value: owned
            - name: email
              value: zfajart@gmail.com
            - name: Stack
              value: project ocp4-cluster-rwlwm
            - name: env_type
              value: ocp4-cluster
            - name: guid
              value: rwlwm
            - name: owner
              value: unknown
            - name: platform
              value: labs
            - name: uuid
              value: cfc63b43-0948-547c-b22a-a8a08b9c6d61
