kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: '108.137.80.76:8082/repository/docker-repository/postgres'
          ports:
            - containerPort: 5432
              protocol: TCP
          envFrom:
            - configMapRef:
                name: postgres-config
      imagePullSecrets:
        - name: nexus-secret

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: postgres-config
  namespace: default
  labels:
    app: postgres
data:
  POSTGRES_DB: mydb
  POSTGRES_PASSWORD: rahasia
  POSTGRES_USER: admin

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres
