kind: PersistentVolume
apiVersion: v1
metadata:
  name: pvc-0e0c9eff-c21f-488d-b2a4-ed8232cf159c
spec:
  capacity:
    storage: 10Gi
  csi:
    driver: openshift-storage.rbd.csi.ceph.com
    volumeHandle: >-
      0001-0011-openshift-storage-0000000000000001-a46ec49e-0d86-11ee-8a44-0a580a820205
    fsType: ext4
    volumeAttributes:
      imageName: csi-vol-a46ec49e-0d86-11ee-8a44-0a580a820205
      csi.storage.k8s.io/pvc/namespace: airbnb
      imageFormat: '2'
      journalPool: ocs-storagecluster-cephblockpool
      clusterID: openshift-storage
      csi.storage.k8s.io/pvc/name: mongodb-data
      imageFeatures: layering
      storage.kubernetes.io/csiProvisionerIdentity: 1687056403372-8081-openshift-storage.rbd.csi.ceph.com
      csi.storage.k8s.io/pv/name: pvc-0e0c9eff-c21f-488d-b2a4-ed8232cf159c
      pool: ocs-storagecluster-cephblockpool
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: openshift-storage
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: openshift-storage
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: airbnb
    name: mongodb-data
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
