apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: workers-chrony-configuration
spec:
  config:
    ignition:
      config: {}
    security:
      tls: {}
    timeouts: {}
    version: 3.2.0
  networkd: {}
  passwd: {}
  storage:
    files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,$(BASE64_OUTPUT)
        mode: 420
        overwrite: true
        path: /etc/chrony.conf
  osImageURL: ''
