apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - type: HTPasswd
      name: users
      mappingMethod: claim
      htpasswd:
        fileData:
          name: htpasswd-secret