apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: vm2
  namespace: storage-intro
spec:
  pvc:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
    storageClassName: ocs-storagecluster-ceph-rbd-virtualization
    volumeMode: Block
  source:
    http:
      url: https://cluster-699d9-qlmtz-image-registry-us-east-2-gfdfqppfxislryvrn.s3.us-east-2.amazonaws.com/helloworld.qcow2
