apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    flavor.template.kubevirt.io/small: 'true'
    kubevirt.io/domain: vm1
    kubevirt.io/size: small
    os.template.kubevirt.io/rhel8.4: 'true'
    workload.template.kubevirt.io/server: 'true'
  name: vm1
  namespace: network-lb
spec:
  architecture: amd64
  domain:
    cpu:
      cores: 1
      maxSockets: 4
      model: host-model
      sockets: 1
      threads: 1
    devices:
      disks:
        - bootOrder: 1
          disk:
            bus: virtio
          name: vm1
        - disk:
            bus: virtio
          name: cloudinitdisk
      interfaces:
        - masquerade: {}
          model: virtio
          name: default
      networkInterfaceMultiqueue: true
      rng: {}
    features:
      acpi:
        enabled: true
    machine:
      type: pc-q35-rhel8.4.0
    memory:
      guest: 2Gi
      maxGuest: 8Gi
    resources:
      requests:
        memory: 2Gi
  evictionStrategy: LiveMigrate
  hostname: vm1
  networks:
    - name: default
      pod: {}
  terminationGracePeriodSeconds: 180
  volumes:
    - dataVolume:
        name: vm1
      name: vm1
    - cloudInitNoCloud:
        userData: |-
          #cloud-config
          hostname: vm1
          fqdn: vm1.local
          create_hostname_file: true
          user: developer
          password: developer
          chpasswd: { expire: False }
          ssh_authorized_keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGtUW3ismHyuCW4CDdTVOOOq6aySdtYenXFWWx7HJa4VTepkG00aaLId9ocra10hc+MB0GTJMCyabDv3i8NKdi6GDH/aOLVsp/Ewy8DEzZMBlJDCt4v2i4/wU4liw6KgEFkZs+5hnqU8d4QzldyGJ5onr+AGvFOKG68CS0BBl40Z1twf1HhCyx8k6nzD2ovlkxWRFZKPAFrtPCBVvQDkOfVFZF+lwzaSztgAjbFZ4A9jqQyUYx4kOJ5DtRef36ucdUdVQale0+8lICl7/gb142SPpYfhxe88/BJScLPRjvVNeu1TxRmoHtVazqnAoRxQYAn2MoI6AG+w6QuZf8f7aL LabGradingKey
      name: cloudinitdisk
