apiVersion: v1
data:
  # Default username and password is 'admin' 'password'. To change this base64 encode another
  # htpasswd string (htpasswd -n -B -b username password) and substitute the below htpasswd value.
  htpasswd: YWRtaW46JDJ5JDA1JGl5NVNsQ2guN3gxSGlabUJZYlVody5Rck0zOVpidks5c3lVSlZtQzZ3V3ViZkE4bTRYdTFhCg==
kind: Secret
metadata:
  name: htpasswd-secret
  namespace: openshift-config
type: Opaque
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - name: htpasswd_provider
      mappingMethod: claim
      type: HTPasswd
      htpasswd:
        fileData:
          name: htpasswd-secret
