apiVersion: velero.io/v1
kind: Backup
metadata:
  name: my-backup
  namespace: openshift-adp
  labels:
    velero.io/storage-location: oadp-dpa-1
spec:
  includedNamespaces:
    - my-project
  storageLocation: oadp-dpa-1
  snapshotVolumes: true
