apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: hello-web
  namespace: web-servers
  annotations:
    description: VM hello-web
  labels:
    app: hello-web
spec:
  runStrategy: Always
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: hello-web
        kubevirt.io/size: small
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          maxSockets: 4
          model: host-model
          sockets: 1
          threads: 1
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: hello-web
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi:
            enabled: true
        memory:
          guest: 2Gi
          maxGuest: 8Gi
        resources:
          requests:
            memory: 2Gi
      evictionStrategy: LiveMigrate
      hostname: hello-web
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - name: hello-web
          dataVolume:
            name: hello-web
        - cloudInitNoCloud:
            userDataBase64: IyEvYmluL2Jhc2gKdXNlcmFkZCAtRyB3aGVlbCBkZXZlbG9wZXIKZWNobyBkZXZlbG9wZXIgfCBwYXNzd2QgLS1zdGRpbiBkZXZlbG9wZXIKcmVzdG9yZWNvbiAvdmFyL3d3dy9odG1sLyo=
          name: cloudinitdisk
