apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-w2bv5-h7jv5
  name: default-router
  namespace: openshift-machine-api
spec:
  replicas: 2
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-w2bv5-h7jv5
      machine.openshift.io/cluster-api-machineset: cluster-w2bv5-h7jv5-default-router-us-east-2c
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-w2bv5-h7jv5
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra
        machine.openshift.io/cluster-api-machineset: cluster-w2bv5-h7jv5-default-router-us-east-2c
    spec:
      taints:
        - key: infra-internal
          effect: NoSchedule
      metadata:
        labels:
          node-role.kubernetes.io/infra: ''
          node: default-router
      providerSpec:
        value:
          ami:
            id: ami-02c627a4f7f3cef78
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 200
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: cluster-w2bv5-h7jv5-worker-profile
          instanceType: c5.xlarge
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: us-east-2c
            region: us-east-2
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - cluster-w2bv5-h7jv5-worker-sg
          subnet:
            filters:
              - name: tag:Name
                values:
                  - cluster-w2bv5-h7jv5-private-us-east-2c
          tags:
            - name: kubernetes.io/cluster/cluster-w2bv5-h7jv5
              value: owned
            - name: email
              value: zfajart@gmail.com
          userDataSecret:
            name: worker-user-data
