apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    machine.openshift.io/GPU: '1'
    machine.openshift.io/memoryMb: '131072'
    machine.openshift.io/vCPU: '32'
  name: cluster-sb682-jb7r6-worker-gpu-eu-west-1b
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-sb682-jb7r6
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-sb682-jb7r6
      machine.openshift.io/cluster-api-machineset: cluster-sb682-jb7r6-worker-gpu-eu-west-1b
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-sb682-jb7r6
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: cluster-sb682-jb7r6-worker-gpu-eu-west-1b
    spec:
      lifecycleHooks: {}
      metadata:
        labels:
          node-role.kubernetes.io/worker: ""
      providerSpec:
        value:
          userDataSecret:
            name: worker-user-data
          placement:
            availabilityZone: eu-west-1b
            region: eu-west-1
          credentialsSecret:
            name: aws-cloud-credentials
          instanceType: p4d.24xlarge
          metadata:
            creationTimestamp: null
          blockDevices:
            - ebs:
                iops: 0
                kmsKey: {}
                volumeSize: 120
                volumeType: gp2
          securityGroups:
            - filters:
                - name: 'tag:Name'
                  values:
                    - cluster-sb682-jb7r6-worker-sg
          kind: AWSMachineProviderConfig
          tags:
            - name: kubernetes.io/cluster/cluster-sb682-jb7r6
              value: owned
            - name: Stack
              value: project ocp4-cluster-sb682
            - name: env_type
              value: ocp4-cluster
            - name: guid
              value: sb682
            - name: owner
              value: unknown
            - name: platform
              value: labs
            - name: uuid
              value: 31d34923-4632-5642-b573-59457440aa71
          deviceIndex: 0
          ami:
            id: ami-080d1b5ac12af223b
          subnet:
            filters:
              - name: 'tag:Name'
                values:
                  - cluster-sb682-jb7r6-private-eu-west-1b
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          iamInstanceProfile:
            id: cluster-sb682-jb7r6-worker-profile