kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: datastore2-for-ocs
provisioner: kubernetes.io/vsphere-volume
parameters:
  datastore: GGDatastore02_Openshift
  diskformat: zeroedthick
reclaimPolicy: Delete
volumeBindingMode: Immediate
