apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    email: 'zfajart@gmail.com'
    privateKeySecretRef:
      name: cluster-issuer-acme-production
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    solvers:
      - dns01:
          route53:
            accessKeyID: 'AKIAUTGCS46F6IXUL7ON'
            hostedZoneID: 'Z09396601IB9VV6QXL9QX'
            region: ap-southeast-1
            secretAccessKeySecretRef:
              key: aws_secret_access_key
              name: cert-manager-aws-creds
        selector:
          dnsZones:
            - 'ocp.fajjjar.my.id'
