global:
  resolve_timeout: 5m
  smtp_from: alerts@ocp4.example.com
  smtp_smarthost: '192.168.50.254:25'
  smtp_hello: localhost
  smtp_auth_username: smtp_training
  smtp_auth_password: Red_H4T@!
  smtp_require_tls: false
inhibit_rules:
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = critical
    target_matchers:
      - severity =~ warning|info
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = warning
    target_matchers:
      - severity = info
  - equal:
      - namespace
    source_matchers:
      - alertname = InfoInhibitor
    target_matchers:
      - severity = info
receivers:
  - name: Default
  - name: Watchdog
  - name: Critical
  - name: 'null'
  - name: email
    email_configs:
      - to: ocp-admins@example.com
route:
  group_by:
    - namespace
  group_interval: 2m
  group_wait: 30s
  receiver: Default
  repeat_interval: 1m
  routes:
    - matchers:
        - alertname = Watchdog
      receiver: Watchdog
    - matchers:
        - alertname = InfoInhibitor
      receiver: 'null'
    - matchers:
        - severity = critical
      receiver: Critical
    - receiver: email
      match:
        alertname: PersistentVolumeUsageNearFull
---
global:
  resolve_timeout: 5m
  smtp_from: alerts@cluster-sh6mk.sandbox2151.opentlc.com
  smtp_smarthost: 'sandbox.smtp.mailtrap.io:25'
  smtp_hello: localhost
  smtp_auth_username: 6900e74dc1d6ec
  smtp_auth_password: 2eab88d050f92d
  smtp_require_tls: true
inhibit_rules:
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = critical
    target_matchers:
      - severity =~ warning|info
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = warning
    target_matchers:
      - severity = info
receivers:
  - name: Critical
  - name: Default
  - name: Watchdog
  - name: email
    email_configs:
      - to: ocp-admins@cluster-sh6mk.sandbox2151.opentlc.com
route:
  group_by:
    - namespace
  group_interval: 2m
  group_wait: 30s
  receiver: Default
  repeat_interval: 1m
  routes:
    - matchers:
        - alertname = Watchdog
      receiver: Watchdog
    - matchers:
        - severity = critical
      receiver: Critical
    - receiver: email
      match:
        alertname: PersistentVolumeUsageNearFull
