apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: Linux bridge on the worker nodes with enp127s0 as a port
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br0
  name: database-network
  namespace: developer-vms
spec:
  config: |-
    {
        "cniVersion": "0.3.1",
        "name": "database-network",
        "type": "bridge",
        "bridge": "br0",
        "ipam": {},
        "macspoofchk": true,
        "preserveDefaultVlan": false
    }
