apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: sakila
    flavor.template.kubevirt.io/small: 'true'
    kubevirt.io/vm: dev-dbaccess
    os.template.kubevirt.io/rhel8.4: 'true'
    vm.kubevirt.io/template: rhel8-server-small
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.26.2
    workload.template.kubevirt.io/server: 'true'
  name: dev-dbaccess
  namespace: developer-vms
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: dev-dbaccess
      spec:
        pvc:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 10Gi
          storageClassName: ocs-external-storagecluster-ceph-rbd-virtualization
          volumeMode: Block
        source:
          http:
            url: http://utility.lab.example.com:8080/openshift4/images/dev-dbaccess.qcow2
  runStrategy: RerunOnFailure
  template:
    metadata:
      creationTimestamp: null
      labels:
        flavor.template.kubevirt.io/small: 'true'
        kubevirt.io/domain: dev-dbaccess
        kubevirt.io/size: small
        os.template.kubevirt.io/rhel8.4: 'true'
        workload.template.kubevirt.io/server: 'true'
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: dev-dbaccess
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
            # - bridge: {}
            #   macAddress: '00:00:00:00:00:01'
            #   model: virtio
            #   name: database
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: pc-q35-rhel8.4.0
        resources:
          requests:
            memory: 2Gi
      evictionStrategy: LiveMigrate
      hostname: dev-dbaccess
      networks:
        - name: default
          pod: {}
        # - multus:
        #     networkName: database-network
        #   name: database
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: dev-dbaccess
          name: dev-dbaccess
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: developer
              password: developer
              chpasswd: { expire: False }
              ssh_authorized_keys:
                - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGtUW3ismHyuCW4CDdTVOOOq6aySdtYenXFWWx7HJa4VTepkG00aaLId9ocra10hc+MB0GTJMCyabDv3i8NKdi6GDH/aOLVsp/Ewy8DEzZMBlJDCt4v2i4/wU4liw6KgEFkZs+5hnqU8d4QzldyGJ5onr+AGvFOKG68CS0BBl40Z1twf1HhCyx8k6nzD2ovlkxWRFZKPAFrtPCBVvQDkOfVFZF+lwzaSztgAjbFZ4A9jqQyUYx4kOJ5DtRef36ucdUdVQale0+8lICl7/gb142SPpYfhxe88/BJScLPRjvVNeu1TxRmoHtVazqnAoRxQYAn2MoI6AG+w6QuZf8f7aL LabGradingKey
          name: cloudinitdisk
