apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-ocp-certificate
  namespace: openshift-ingress
spec:
  commonName: 'apps.development.sandbox1111.opentlc.com'
  dnsNames:
    - 'apps.development.sandbox1111.opentlc.com'
    - '*.apps.development.sandbox1111.opentlc.com'
  secretName: apps-ocp-lab-tls
  isCA: false
  issuerRef:
    group: cert-manager.io
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
