apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-ec2
spec:
  acme:
    email: ''
    privateKeySecretRef:
      name: cluster-issuer-acme-production
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    solvers:
      - dns01:
          route53:
            accessKeyID: ''
            hostedZoneID: ''
            region: us-east-2
            secretAccessKeySecretRef:
              key: aws_secret_access_key
              name: cert-manager-aws-creds
        selector:
          dnsZones:
            - api.cluster.domain.io
            - apps.cluster.domain.io
