apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  ### additional configuration options can be set here
  defaultCertificate:
    name: app-router-certs
  ###
