apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-ec2
spec:
  acme:
    email: ''
    privateKeySecretRef:
      name: cluster-issuer-acme-production
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    solvers:
      - dns01:
          route53:
            accessKeyID: ''
            hostedZoneID: Z0215571AK33HUSU581L
            region: ap-southeast-1
            secretAccessKeySecretRef:
              key: aws_secret_access_key
              name: cert-manager-aws-creds
        selector:
          dnsZones:
            - api.cluster-6bpmb.6bpmb.sandbox1882.domain.com
            - apps.cluster-6bpmb.6bpmb.sandbox1882.domain.com